[workspace]
authors = ["nichmor <nichita@prefix.dev>"]
channels = ["conda-forge"]
description = "Showcases trusted publishing to prefix.dev with a pixi-built C++/SDL package."
name = "sdl_example"
platforms = ["linux-64", "osx-64", "osx-arm64", "win-64"]
preview = ["pixi-build"]

[package]
name = "sdl_example"
version = "0.1.0"

[package.build]
backend = { name = "pixi-build-cmake", version = "*" }

[package.host-dependencies]
sdl2 = "2.26.5.*"

[package.run-dependencies]
sdl2 = "2.26.5.*"

[tasks.start]
cmd = ".build/bin/sdl_example"
depends-on = ["build"]

[dependencies]
cmake = ">=3.31.6,<4"
sdl2 = "2.26.5.*"

[feature.build.dependencies]
cxx-compiler = ">=1.9.0, <2"
ninja = ">=1.12.1,<2"

[feature.build.tasks.configure]
cmd = [
  "cmake",
  "-GNinja",
  "-S.",
  "-B.build",
]
inputs = ["CMakeLists.txt"]
outputs = [".build/CMakeFiles/"]

[feature.build.tasks.build]
cmd = ["cmake", "--build", ".build"]
depends-on = ["configure"]
inputs = ["CMakeLists.txt", "src/*"]
outputs = [".build/bin/sdl_example"]

[environments]
build = ["build"]
